version: "3.8"

services:
    postgres:
        image: "postgres:14.4"
        container_name: postgres
        environment:
            POSTGRES_USER: "memo_user"
            POSTGRES_PASSWORD: "gWZJPiXy6q"
            PGDATA: "/data/postgres"
        ports:
            - "15432:5432"
        restart: unless-stopped
    
    memo_auth:
        depends_on:
            - postgres
        container_name: memo_auth
        build:
            context: ./Memo.Auth
      
    memo_notes:
        depends_on:
            - postgres
        container_name: memo_notes
        build:
            context: ./Memo.Notes
            
    memo_mvc:
        depends_on:
            - memo_auth
            - memo_notes
        build:
            context: ./Memo.Mvc
        ports:
            - "5000:80"